version: "3.3"

services:

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crimenyc
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crimenyc
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crimenyc"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-backend:
    image: python:3.9-slim
    container_name: flask-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    command: flask run --host=0.0.0.0

  react-frontend:
    image: node:16
    container_name: react-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      flask-backend:
        condition: service_started

  flask-ia:
    image: python:3.9-slim
    container_name: flask-ia
    build:
      context: ./ia
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./ia:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      kafka:
        condition: service_healthy
    command: flask run --host=0.0.0.0

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,INTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, INTERNAL://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CREATE_TOPICS: "send-data:1:1,train-data:1:1"
      KAFKA_LOG_RETENTION_BYTES: 1073741824
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-master:
    build:
      context: ./spark-app
      dockerfile: Dockerfile
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark-app:/app
    environment:
      - INIT_DAEMON_STEP=setup_spark
    depends_on:
      postgres:
        condition: service_healthy

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  test_spark:
    build:
      context: ./test_spark
    container_name: test_spark
    volumes:
      - ./test_spark:/app
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    tty: true

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile-superset
    container_name: superset
    restart: always
    ports:
      - "8089:8088"
    environment:
      - SUPERSET_SECRET_KEY=mysecretkey
      - PYTHONPATH=/app/pythonpath
    depends_on:
      - postgres
    volumes:
      - ./superset_home:/app/superset_home
    command: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "

volumes: 
  postgres-data: