# superset_config.py

FEATURE_FLAGS = {
    "DASHBOARD_RBAC": True,
}

TESTING = True

ENABLE_PUBLIC_REGISTRATION = True
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = "Gamma"
AUTH_USER_REGISTRATION_EMAIL_MANDATORY = False
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_REGISTERABLE = False  # Ne sert à rien si ENABLE_PUBLIC_REGISTRATION est True

# Config mail fictive pour débloquer l'inscription
MAIL_SERVER = 'localhost'
MAIL_PORT = 25
MAIL_USE_TLS = False
MAIL_USE_SSL = False
MAIL_USERNAME = ''
MAIL_PASSWORD = ''
MAIL_DEFAULT_SENDER = 'noreply_superset@gmail.com'

RECAPTCHA_PUBLIC_KEY = ""
RECAPTCHA_PRIVATE_KEY = ""
WTF_CSRF_ENABLED = False