FROM apache/superset:latest

USER root

RUN apt-get update && \
    apt-get install -y build-essential libsasl2-dev python3-dev libldap2-dev libssl-dev && \
    pip install --no-cache-dir \
        psycopg2-binary \
        pyhive[hive] \
        thrift \
        thrift-sasl \
        sasl \
        pandas \
        pyopenssl \
        pymongo && \
    apt-get clean

USER superset
